2025-01-19 09:50:03.351 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
2025-01-19 09:50:03.352 | INFO     | sc2.controller:create_game:37 - Creating new game
2025-01-19 09:50:03.353 | INFO     | sc2.controller:create_game:38 - Map:     InterloperAIE
2025-01-19 09:50:03.354 | INFO     | sc2.controller:create_game:39 - Players: Bot LadderBot(Terran), Computer CheatVision(Zerg, Macro)
2025-01-19 09:50:03.356 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
2025-01-19 09:50:13.648 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
2025-01-19 09:50:13.650 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot LadderBot(Terran)
2025-01-19 09:50:14.292 | 00:00    0ms    0M    0G  12/ 15U [Version] 5.0.14.93333
2025-01-19 09:50:14.468 | 00:00    0ms    0M    0G  12/ 15U [ZoneManager] Map set to: MapName.Unknown from name: Незваный гость РВ and hash: 3802010.
2025-01-19 09:50:15.559 | ERROR    | sc2.main:initialize_first_step:140 - Caught unknown exception in AI on_start: 
Traceback (most recent call last):

  File "d:\Bots\Banshee\run.py", line 18, in <module>
    main()
    └ <function main at 0x000001F8234AFA60>

  File "d:\Bots\Banshee\run.py", line 13, in main
    result, opponentid = run_ladder_game(protoss_bot)
                         │               └ <sc2.player.Bot object at 0x000001F8220E8690>
                         └ <function run_ladder_game at 0x000001F807DEE700>

  File "d:\Bots\Banshee\ladder.py", line 39, in run_ladder_game
    return stand_alone_game(bot), None
           │                └ <sc2.player.Bot object at 0x000001F8220E8690>
           └ <function stand_alone_game at 0x000001F820C24540>

  File "d:\Bots\Banshee\ladder.py", line 166, in stand_alone_game
    return sc2.main.run_game(sc2.maps.get(map_name), [bot, Computer(Race.Zerg, Difficulty.CheatVision, AIBuild.Macro)], realtime=False,)
           │   │    │        │   │    │   │           │    │        │    │     │          │            │       └ <AIBuild.Macro: 5>
           │   │    │        │   │    │   │           │    │        │    │     │          │            └ <enum 'AIBuild'>
           │   │    │        │   │    │   │           │    │        │    │     │          └ <Difficulty.CheatVision: 8>
           │   │    │        │   │    │   │           │    │        │    │     └ <enum 'Difficulty'>
           │   │    │        │   │    │   │           │    │        │    └ <Race.Zerg: 2>
           │   │    │        │   │    │   │           │    │        └ <enum 'Race'>
           │   │    │        │   │    │   │           │    └ <class 'sc2.player.Computer'>
           │   │    │        │   │    │   │           └ <sc2.player.Bot object at 0x000001F8220E8690>
           │   │    │        │   │    │   └ 'InterloperAIE'
           │   │    │        │   │    └ <function get at 0x000001F820CA89A0>
           │   │    │        │   └ <module 'sc2.maps' from 'd:\\Bots\\Banshee\\sc2\\maps.py'>
           │   │    │        └ <module 'sc2' from 'd:\\Bots\\Banshee\\sc2\\__init__.py'>
           │   │    └ <function run_game at 0x000001F820DE8F40>
           │   └ <module 'sc2.main' from 'd:\\Bots\\Banshee\\sc2\\main.py'>
           └ <module 'sc2' from 'd:\\Bots\\Banshee\\sc2\\__init__.py'>

  File "d:\Bots\Banshee\sc2\main.py", line 496, in run_game
    result: Result = asyncio.run(_host_game(map_settings, players, **kwargs))
                     │       │   │          │             │          └ {'realtime': False}
                     │       │   │          │             └ [<sc2.player.Bot object at 0x000001F8220E8690>, <sc2.player.Computer object at 0x000001F8234EFBD0>]
                     │       │   │          └ Map(D:\StarCraft II\maps\InterloperAIE.SC2Map)
                     │       │   └ <function _host_game at 0x000001F820DE8AE0>
                     │       └ <function run at 0x000001F809A46200>
                     └ <module 'asyncio' from 'C:\\Users\\Lena\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\__init__.py'>

  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object _host_game at 0x000001F82344CF60>
           │      └ <function Runner.run at 0x000001F809AB6200>
           └ <asyncio.runners.Runner object at 0x000001F821CCE3D0>
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<_host_game() running at d:\Bots\Banshee\sc2\main.py:369> cb=[_run_until_complete_cb() at C:...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x000001F809AAFCE0>
           │    └ <ProactorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x000001F821CCE3D0>
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x000001F809FAFCE0>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x000001F809AB5A80>
    └ <ProactorEventLoop running=True closed=False debug=False>
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x000001F809A0B060>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "C:\Users\Lena\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "d:\Bots\Banshee\sc2\main.py", line 369, in _host_game
    result = await _play_game(players[0], client, realtime, portconfig, game_time_limit, rgb_render_config)
                   │          │           │       │         │           │                └ None
                   │          │           │       │         │           └ None
                   │          │           │       │         └ None
                   │          │           │       └ False
                   │          │           └ <sc2.client.Client object at 0x000001F821B45510>
                   │          └ [<sc2.player.Bot object at 0x000001F8220E8690>, <sc2.player.Computer object at 0x000001F8234EFBD0>]
                   └ <function _play_game at 0x000001F820DE8900>

  File "d:\Bots\Banshee\sc2\main.py", line 226, in _play_game
    result = await _play_game_ai(client, player_id, player.ai, realtime, game_time_limit)
                   │             │       │          │      │   │         └ None
                   │             │       │          │      │   └ False
                   │             │       │          │      └ <dummy.dummy1.LadderBot object at 0x000001F807B0DF50>
                   │             │       │          └ <sc2.player.Bot object at 0x000001F8220E8690>
                   │             │       └ 1
                   │             └ <sc2.client.Client object at 0x000001F821B45510>
                   └ <function _play_game_ai at 0x000001F820DE87C0>

  File "d:\Bots\Banshee\sc2\main.py", line 145, in _play_game_ai
    result = await initialize_first_step()
                   └ <function _play_game_ai.<locals>.initialize_first_step at 0x000001F8234F4E00>

> File "d:\Bots\Banshee\sc2\main.py", line 136, in initialize_first_step
    await ai.on_start()
          │  └ <function KnowledgeBot.on_start at 0x000001F820EBA7A0>
          └ <dummy.dummy1.LadderBot object at 0x000001F807B0DF50>

  File "d:\Bots\Banshee\sharpy\knowledges\knowledge_bot.py", line 71, in on_start
    await self.knowledge.start()
          │    │         └ <function Knowledge.start at 0x000001F820E72A20>
          │    └ <sharpy.knowledges.knowledge.Knowledge object at 0x000001F807B5B750>
          └ <dummy.dummy1.LadderBot object at 0x000001F807B0DF50>

  File "d:\Bots\Banshee\sharpy\knowledges\knowledge.py", line 151, in start
    await manager.post_start()
          │       └ <function ActManager.post_start at 0x000001F820C78D60>
          └ <sharpy.managers.core.act_manager.ActManager object at 0x000001F8235527D0>

  File "d:\Bots\Banshee\sharpy\managers\core\act_manager.py", line 25, in post_start
    self._act = await self._act_or_func()
    │                 │    └ <bound method Banshees.create_plan of <dummy.dummy1.LadderBot object at 0x000001F807B0DF50>>
    │                 └ <sharpy.managers.core.act_manager.ActManager object at 0x000001F8235527D0>
    └ <sharpy.managers.core.act_manager.ActManager object at 0x000001F8235527D0>

  File "d:\Bots\Banshee\dummy\dummy1.py", line 217, in create_plan
    Step(
    └ <class 'sharpy.plans.build_step.Step'>

  File "d:\Bots\Banshee\sharpy\plans\build_step.py", line 25, in __init__
    assert skip is None or isinstance(skip, RequireBase) or isinstance(skip, Callable)
           │                          │     │                          │     └ typing.Callable
           │                          │     │                          └ <sharpy.plans.acts.terran.terran_unit.TerranUnit object at 0x000001F823D456D0>
           │                          │     └ <class 'sharpy.plans.require.require_base.RequireBase'>
           │                          └ <sharpy.plans.acts.terran.terran_unit.TerranUnit object at 0x000001F823D456D0>
           └ <sharpy.plans.acts.terran.terran_unit.TerranUnit object at 0x000001F823D456D0>

AssertionError: assert skip is None or isinstance(skip, RequireBase) or isinstance(skip, Callable)
2025-01-19 09:50:15.615 | ERROR    | sc2.main:initialize_first_step:141 - Resigning due to previous error
2025-01-19 09:50:15.616 | Result: Defeat
2025-01-19 09:50:15.616 | Duration: 00:00
2025-01-19 09:50:15.617 | Step time avg: 0
2025-01-19 09:50:15.617 | Step time max: 0
2025-01-19 09:50:15.618 | [LostUnitsContents] My lost units minerals and gas: (0, 0)
2025-01-19 09:50:15.619 | [LostUnitsContents] My lost units minerals by score: 0.0
2025-01-19 09:50:15.619 | [LostUnitsContents] Enemy lost units minerals and gas: (0, 0)
2025-01-19 09:50:15.620 | [LostUnitsContents] Enemy lost units minerals by score: 0.0
2025-01-19 09:50:15.621 | [GameAnalyzerEnd] Own units:
2025-01-19 09:50:15.621 | [GameAnalyzerEnd] Enemy units:
2025-01-19 09:50:15.622 | [GameAnalyzerEnd] Minerals max 0 Average 0
2025-01-19 09:50:15.622 | [GameAnalyzerEnd] Vespene max 0 Average 0
2025-01-19 09:50:15.623 | INFO     | sc2.main:_play_game:228 - Result for player 1 - Bot LadderBot(Terran): Defeat
2025-01-19 09:50:16.817 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was Status.in_game)
2025-01-19 09:50:16.831 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.quit (was Status.launched)
2025-01-19 09:50:16.832 | INFO     | sc2.sc2process:_close_connection:231 - Closing connection at 54784...
2025-01-19 09:50:16.833 | INFO     | sc2.sc2process:kill_all:33 - kill_switch: Process cleanup for 1 processes
